repos:
  - repo: local
    hooks:
      - id: make-fmt
        name: Run Makefile format
        entry: make format
        language: system
        pass_filenames: false
        types: [ shell ]
      - id: make-fix
        name: Run Makefile lint-fix
        entry: make lint-fix
        language: system
        pass_filenames: false
        types: [ shell ]
      - id: make-lint
        name: Run Makefile lint-fix
        entry: make lint
        language: system
        pass_filenames: false
        types: [ shell ]